"""add_pending_status_to_borrow_enum

Revision ID: 6cf21d0f8748
Revises: 5c2b7fcfa8ec
Create Date: 2025-11-25 10:51:14.765265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf21d0f8748'
down_revision = '5c2b7fcfa8ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
