"""add_news_category_field

Revision ID: 84ddb26b4ff8
Revises: 3473f959e9fe
Create Date: 2025-11-24 13:46:16.630569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ddb26b4ff8'
down_revision = '3473f959e9fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type first
    newscategory_enum = sa.Enum('EVENT', 'MAINTENANCE', 'GENERAL', name='newscategory')
    newscategory_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('books', 'total_reviews',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('news', sa.Column('category', newscategory_enum, nullable=False, server_default='GENERAL'))
    op.drop_index(op.f('ix_reservations_book_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reviews_book_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviews_book_id'), 'reviews', ['book_id'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_index(op.f('ix_reservations_book_id'), 'reservations', ['book_id'], unique=False)
    op.drop_column('news', 'category')

    # Drop ENUM type
    sa.Enum('EVENT', 'MAINTENANCE', 'GENERAL', name='newscategory').drop(op.get_bind(), checkfirst=True)

    op.alter_column('books', 'total_reviews',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
