"""add_cancelled_status_to_borrow_enum

Revision ID: a94dbe6d65c7
Revises: 6cf21d0f8748
Create Date: 2025-11-25 11:06:37.280833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94dbe6d65c7'
down_revision = '6cf21d0f8748'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
