"""add_deposit_fee_to_books

Revision ID: 5c2b7fcfa8ec
Revises: 7992d52491d6
Create Date: 2025-11-25 09:57:11.914971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2b7fcfa8ec'
down_revision = '7992d52491d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('deposit_fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'deposit_fee')
    # ### end Alembic commands ###
