"""Add cascade delete to reservations book_id foreign key

Revision ID: d59ba2d25a62
Revises: a94dbe6d65c7
Create Date: 2025-11-27 10:18:36.048218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59ba2d25a62'
down_revision = 'a94dbe6d65c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reservations_book_id_fkey'), 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(op.f('reservations_book_id_fkey'), 'reservations', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###
